version: '1'
services:
    db:
        container_name: patchy-db
        image: postgres
        ports:
          - '5433:5432'
        volumes:
          - db:/var/lib/postgrsql/data
        env_file:
          - .env
volumes:
  db:
    driver: local
