version: '1'
services:
    db:
        container_name: patchy-db
        image: postgres
        environment:
          - POSTGRES_USER=postgres
          - POSTGRES_PASSWORD=postgres
        ports:
          - '5433:5432'
        volumes:
          - db:/var/lib/postgrsql/data
volumes:
  db:
    driver: local
